// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Analytic struct {
	ID         int64     `json:"id"`
	TemplateID string    `json:"template_id"`
	VersionID  string    `json:"version_id"`
	Action     string    `json:"action"`
	Timestamp  time.Time `json:"timestamp"`
	Status     string    `json:"status"`
}

type Job struct {
	ID            int64      `json:"id"`
	Type          string     `json:"type"`
	TemplateID    string     `json:"template_id"`
	VersionNumber *int64     `json:"version_number"`
	Status        string     `json:"status"`
	Progress      int64      `json:"progress"`
	StartedAt     time.Time  `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	ErrorMessage  *string    `json:"error_message"`
	Metadata      string     `json:"metadata"`
}

type Template struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TemplateVersion struct {
	ID            string    `json:"id"`
	TemplateID    string    `json:"template_id"`
	VersionNumber int64     `json:"version_number"`
	ObjectKey     string    `json:"object_key"`
	FileSize      *int64    `json:"file_size"`
	FileHash      *string   `json:"file_hash"`
	CreatedAt     time.Time `json:"created_at"`
}
