// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createAnalytic = `-- name: CreateAnalytic :one
INSERT INTO "analytics" ("id", "template_id", "version_id", "action", "timestamp", "status")
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, template_id, version_id, "action", timestamp, status
`

type CreateAnalyticParams struct {
	ID         int64     `json:"id"`
	TemplateID string    `json:"template_id"`
	VersionID  string    `json:"version_id"`
	Action     string    `json:"action"`
	Timestamp  time.Time `json:"timestamp"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateAnalytic(ctx context.Context, arg CreateAnalyticParams) (Analytic, error) {
	row := q.db.QueryRowContext(ctx, createAnalytic,
		arg.ID,
		arg.TemplateID,
		arg.VersionID,
		arg.Action,
		arg.Timestamp,
		arg.Status,
	)
	var i Analytic
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionID,
		&i.Action,
		&i.Timestamp,
		&i.Status,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO "jobs" ("type", "template_id", "version_number", "status", "progress", "started_at", "completed_at", "error_message", "metadata")
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, type, template_id, version_number, status, progress, started_at, completed_at, error_message, metadata
`

type CreateJobParams struct {
	Type          string     `json:"type"`
	TemplateID    string     `json:"template_id"`
	VersionNumber *int64     `json:"version_number"`
	Status        string     `json:"status"`
	Progress      int64      `json:"progress"`
	StartedAt     time.Time  `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	ErrorMessage  *string    `json:"error_message"`
	Metadata      string     `json:"metadata"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Type,
		arg.TemplateID,
		arg.VersionNumber,
		arg.Status,
		arg.Progress,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.Metadata,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TemplateID,
		&i.VersionNumber,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.Metadata,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO "templates" ("id", "name", "description")
VALUES (?, ?, ?)
RETURNING id, name, description, created_at, updated_at
`

type CreateTemplateParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate, arg.ID, arg.Name, arg.Description)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateVersion = `-- name: CreateTemplateVersion :one
INSERT INTO "template_versions" ("id", "template_id", "version_number", "object_key", "file_size", "file_hash")
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, template_id, version_number, object_key, file_size, file_hash, created_at
`

type CreateTemplateVersionParams struct {
	ID            string  `json:"id"`
	TemplateID    string  `json:"template_id"`
	VersionNumber int64   `json:"version_number"`
	ObjectKey     string  `json:"object_key"`
	FileSize      *int64  `json:"file_size"`
	FileHash      *string `json:"file_hash"`
}

func (q *Queries) CreateTemplateVersion(ctx context.Context, arg CreateTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRowContext(ctx, createTemplateVersion,
		arg.ID,
		arg.TemplateID,
		arg.VersionNumber,
		arg.ObjectKey,
		arg.FileSize,
		arg.FileHash,
	)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM "jobs" WHERE "id" = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM "templates" WHERE "id" = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const deleteTemplateVersion = `-- name: DeleteTemplateVersion :exec
DELETE FROM "template_versions" WHERE "id" = ?
`

func (q *Queries) DeleteTemplateVersion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateVersion, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, description, created_at, updated_at FROM templates
WHERE "id" = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateVersion = `-- name: GetTemplateVersion :one
SELECT id, template_id, version_number, object_key, file_size, file_hash, created_at FROM "template_versions"
WHERE (
  ("template_id" = ? AND "version_number" = ?) OR
  ("object_key" = ?)
)
`

type GetTemplateVersionParams struct {
	TemplateID    string `json:"template_id"`
	VersionNumber int64  `json:"version_number"`
	ObjectKey     string `json:"object_key"`
}

func (q *Queries) GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRowContext(ctx, getTemplateVersion, arg.TemplateID, arg.VersionNumber, arg.ObjectKey)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.ObjectKey,
		&i.FileSize,
		&i.FileHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAnalytics = `-- name: ListAnalytics :many
SELECT id, template_id, version_id, "action", timestamp, status FROM "analytics"
ORDER BY "timestamp" DESC
LIMIT ?
OFFSET ?
`

type ListAnalyticsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAnalytics(ctx context.Context, arg ListAnalyticsParams) ([]Analytic, error) {
	rows, err := q.db.QueryContext(ctx, listAnalytics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analytic{}
	for rows.Next() {
		var i Analytic
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.VersionID,
			&i.Action,
			&i.Timestamp,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, template_id, version_number, status, progress, started_at, completed_at, error_message, metadata FROM "jobs"
ORDER BY "created_at" DESC
LIMIT ?2
OFFSET ?1
`

type ListJobsParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TemplateID,
			&i.VersionNumber,
			&i.Status,
			&i.Progress,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateVersions = `-- name: ListTemplateVersions :many
SELECT id, template_id, version_number, object_key, file_size, file_hash, created_at FROM "template_versions"
WHERE "template_id" = ?
`

func (q *Queries) ListTemplateVersions(ctx context.Context, templateID string) ([]TemplateVersion, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateVersions, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateVersion{}
	for rows.Next() {
		var i TemplateVersion
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.VersionNumber,
			&i.ObjectKey,
			&i.FileSize,
			&i.FileHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, created_at, updated_at FROM templates
WHERE (
    "name" LIKE '%' || ?1 || '%' OR
    "description" LIKE '%' || ?1 || '%'  OR
    ?1 IS NULL 
)
ORDER BY created_at DESC
LIMIT ?3
OFFSET ?2
`

type ListTemplatesParams struct {
	Search *string `json:"search"`
	Offset int64   `json:"offset"`
	Limit  int64   `json:"limit"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET 
  "status" = COALESCE(?1, "status"),
  "progress" = COALESCE(?2, "progress"),
  "completed_at" = COALESCE(?3, "completed_at"),
  "error_message" = COALESCE(?4, "error_message")
WHERE "id" = ?5
RETURNING id, type, template_id, version_number, status, progress, started_at, completed_at, error_message, metadata
`

type UpdateJobParams struct {
	Status       *string    `json:"status"`
	Progress     *int64     `json:"progress"`
	CompletedAt  *time.Time `json:"completed_at"`
	ErrorMessage *string    `json:"error_message"`
	ID           int64      `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.Status,
		arg.Progress,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TemplateID,
		&i.VersionNumber,
		&i.Status,
		&i.Progress,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.Metadata,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates 
SET "name" = ?, "description" = ? 
WHERE "id" = ? 
RETURNING id, name, description, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate, arg.Name, arg.Description, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
